use std::collections::BTreeSet;

use anyhow::{bail, Result};
use heck::{ToPascalCase, ToSnakeCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::{
    config::Config,
    query::{Cardinality, Query, TypeSpec},
};

use super::{format_tokens, Renderer};

pub struct D1Renderer;

impl Renderer for D1Renderer {
    fn validate_config(_config: &Config, queries: &[Query]) -> Result<()> {
        for query in queries {
            if let Some(skips) = &query.instrument_skip {
                let parameters = query
                    .parameters
                    .iter()
                    .map(|parameter| parameter.sql_name.as_str())
                    .collect::<BTreeSet<_>>();
                for skipped in skips.iter().filter(|name| name.as_str() != "*") {
                    if !parameters.contains(skipped.as_str()) {
                        bail!(
                            "{}: D1 instrumentation skips unknown parameter `{skipped}`",
                            query.context()
                        );
                    }
                }
            }
        }
        Ok(())
    }

    fn render_module(queries: &[Query], config: &Config) -> Result<String> {
        let blocks = queries
            .iter()
            .map(|query| render_query(query, config.instrument_by_default))
            .collect::<Result<Vec<_>>>()?;
        format_tokens(quote! {
            // Auto-generated by d1c. Do not edit.
            use worker::D1Database;
            use worker::Result;

            #(#blocks)*
        })
    }
}

fn render_query(query: &Query, instrument: bool) -> Result<TokenStream> {
    let row = render_row(query);
    let function = render_function(query, instrument)?;
    Ok(quote! { #row #function })
}

fn render_row(query: &Query) -> TokenStream {
    if matches!(query.cardinality, Cardinality::Exec | Cardinality::Scalar) {
        return TokenStream::new();
    }
    let name = format_ident!("{}Row", query.name.to_pascal_case());
    let fields = query.columns.iter().map(|column| {
        let field = format_ident!("{}", column.rust_name);
        let rust_type = &column.rust_type.syntax;
        quote! { pub #field: #rust_type }
    });
    quote! {
        #[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
        pub struct #name { #(#fields,)* }
    }
}

fn render_function(query: &Query, instrument: bool) -> Result<TokenStream> {
    let function = format_ident!("{}", query.rust_name);
    let sql = &query.positional_sql;
    let arguments = query
        .parameters
        .iter()
        .map(|parameter| {
            let name = format_ident!("{}", parameter.rust_name);
            let rust_type =
                d1_input_type(parameter.rust_type.as_ref().expect("analyzed parameter"));
            quote! { #name: #rust_type }
        })
        .collect::<Vec<_>>();
    let argument_names = query
        .parameters
        .iter()
        .map(|parameter| format_ident!("{}", parameter.rust_name))
        .collect::<Vec<_>>();
    let bindings = query
        .parameters
        .iter()
        .map(|parameter| {
            let name = format_ident!("{}", parameter.rust_name);
            d1_binding(
                parameter.rust_type.as_ref().expect("analyzed parameter"),
                &name,
            )
        })
        .collect::<Vec<_>>();
    let bind = if bindings.is_empty() {
        TokenStream::new()
    } else {
        quote! { let stmt = stmt.bind(&[#(#bindings),*])?; }
    };

    let scalar_type = query.columns.first().map(|column| {
        let syntax = &column.rust_type.syntax;
        quote! { #syntax }
    });
    let row_name = format_ident!("{}Row", query.name.to_pascal_case());
    let return_type = match query.cardinality {
        Cardinality::One => quote! { Result<Option<#row_name>> },
        Cardinality::Many => quote! { Result<Vec<#row_name>> },
        Cardinality::Exec => quote! { Result<()> },
        Cardinality::Scalar => {
            let scalar_type = scalar_type.as_ref().expect("analyzed scalar column");
            quote! { Result<Option<#scalar_type>> }
        }
    };
    let execute = match query.cardinality {
        Cardinality::One => quote! { Ok(stmt.first::<#row_name>(None).await?) },
        Cardinality::Many => quote! {
            let result = stmt.all().await?;
            Ok(result.results::<#row_name>()?)
        },
        Cardinality::Exec => quote! {
            stmt.run().await?;
            Ok(())
        },
        Cardinality::Scalar => {
            let column = &query.columns[0].sql_name;
            let scalar_type = scalar_type.as_ref().expect("analyzed scalar column");
            quote! { Ok(stmt.first::<#scalar_type>(Some(#column)).await?) }
        }
    };
    let instrumentation = render_instrumentation(query, instrument);

    if query.generate_statement {
        let statement_function = format_ident!("{}_stmt", query.rust_name);
        Ok(quote! {
            pub fn #statement_function(d1: &D1Database, #(#arguments),*) -> Result<worker::D1PreparedStatement> {
                let stmt = d1.prepare(#sql);
                #bind
                Ok(stmt)
            }

            #instrumentation
            pub async fn #function(d1: &D1Database, #(#arguments),*) -> #return_type {
                let stmt = #statement_function(d1, #(#argument_names),*)?;
                #execute
            }
        })
    } else {
        Ok(quote! {
            #instrumentation
            pub async fn #function(d1: &D1Database, #(#arguments),*) -> #return_type {
                let stmt = d1.prepare(#sql);
                #bind
                #execute
            }
        })
    }
}

fn render_instrumentation(query: &Query, enabled: bool) -> TokenStream {
    if !enabled {
        return TokenStream::new();
    }
    let span = format!("d1c.{}", query.name.to_snake_case());
    let skipped = match &query.instrument_skip {
        Some(items) if items.iter().any(|item| item == "*") => query
            .parameters
            .iter()
            .map(|parameter| format_ident!("{}", parameter.rust_name))
            .collect::<Vec<_>>(),
        Some(items) => items
            .iter()
            .map(|item| format_ident!("{}", item.to_snake_case()))
            .collect(),
        None => Vec::new(),
    };
    quote! { #[tracing::instrument(name = #span, skip(d1 #(, #skipped)*))] }
}

fn d1_input_type(rust_type: &TypeSpec) -> TokenStream {
    match rust_type.source.as_str() {
        "String" => quote! { &str },
        "Vec<u8>" => quote! { &[u8] },
        "Option<String>" => quote! { Option<&str> },
        "Option<Vec<u8>>" => quote! { Option<&[u8]> },
        _ => {
            let syntax = &rust_type.syntax;
            quote! { #syntax }
        }
    }
}

fn d1_binding(rust_type: &TypeSpec, name: &proc_macro2::Ident) -> TokenStream {
    match rust_type.source.as_str() {
        "i64" => quote! { (#name as f64).into() },
        "Option<i64>" => quote! {
            match #name {
                Some(value) => (value as f64).into(),
                None => worker::wasm_bindgen::JsValue::NULL,
            }
        },
        source if source.starts_with("Option<") => quote! {
            match #name {
                Some(value) => value.into(),
                None => worker::wasm_bindgen::JsValue::NULL,
            }
        },
        _ => quote! { #name.into() },
    }
}
