mod d1;
mod rusqlite;

use anyhow::Result;

use crate::{
    config::{Config, Target},
    query::Query,
};

pub trait Renderer {
    fn validate_config(config: &Config, queries: &[Query]) -> Result<()>;
    fn render_module(queries: &[Query], config: &Config) -> Result<String>;
}

pub fn render_module(queries: &[Query], config: &Config) -> Result<String> {
    match config.target {
        Target::D1 => {
            d1::D1Renderer::validate_config(config, queries)?;
            d1::D1Renderer::render_module(queries, config)
        }
        Target::Rusqlite => {
            rusqlite::RusqliteRenderer::validate_config(config, queries)?;
            rusqlite::RusqliteRenderer::render_module(queries, config)
        }
    }
}

pub(crate) fn format_tokens(tokens: proc_macro2::TokenStream) -> Result<String> {
    let file = syn::parse2::<syn::File>(tokens)?;
    Ok(format!(
        "// Auto-generated by d1c. Do not edit.\n\n{}",
        prettyplease::unparse(&file)
    ))
}
