mod d1;
mod rusqlite;

use std::{
    io::Write,
    path::Path,
    process::{Command, Stdio},
};

use anyhow::{bail, Context, Result};

use crate::{
    config::{Config, Target},
    query::Query,
};

pub trait Renderer {
    fn validate_config(config: &Config, queries: &[Query]) -> Result<()>;
    fn render_module(queries: &[Query], config: &Config, project_dir: &Path) -> Result<String>;
}

pub fn render_module(queries: &[Query], config: &Config, project_dir: &Path) -> Result<String> {
    match config.target {
        Target::D1 => {
            d1::D1Renderer::validate_config(config, queries)?;
            d1::D1Renderer::render_module(queries, config, project_dir)
        }
        Target::Rusqlite => {
            rusqlite::RusqliteRenderer::validate_config(config, queries)?;
            rusqlite::RusqliteRenderer::render_module(queries, config, project_dir)
        }
    }
}

pub(crate) fn format_tokens(
    tokens: proc_macro2::TokenStream,
    project_dir: &Path,
) -> Result<String> {
    let file = syn::parse2::<syn::File>(tokens)?;
    let source = format!(
        "// Auto-generated by d1c. Do not edit.\n\n{}",
        prettyplease::unparse(&file)
    );
    format_rust(&source, project_dir)
}

pub(crate) fn format_rust(source: &str, project_dir: &Path) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--emit", "stdout", "--edition", "2021"])
        .current_dir(project_dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("start rustfmt; d1c generation requires rustfmt on PATH")?;
    child
        .stdin
        .take()
        .context("open rustfmt stdin")?
        .write_all(source.as_bytes())
        .context("write generated Rust to rustfmt")?;
    let output = child.wait_with_output().context("wait for rustfmt")?;
    if !output.status.success() {
        bail!(
            "rustfmt failed while formatting generated Rust: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    String::from_utf8(output.stdout).context("rustfmt emitted non-UTF-8 output")
}
