use std::path::Path;

use anyhow::{bail, Result};
use heck::{ToPascalCase, ToShoutySnakeCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::{
    config::Config,
    query::{Cardinality, Query, TypeSpec},
};

use super::{format_tokens, Renderer};

pub struct RusqliteRenderer;

impl Renderer for RusqliteRenderer {
    fn validate_config(config: &Config, queries: &[Query]) -> Result<()> {
        if config.instrument_by_default {
            bail!("target rusqlite does not support D1 tracing instrumentation");
        }
        if let Some(query) = queries.iter().find(|query| query.instrument_skip.is_some()) {
            bail!(
                "{}: -- instrument: is only valid for target d1",
                query.context()
            );
        }
        if let Some(query) = queries.iter().find(|query| query.generate_statement) {
            bail!("{}: :stmt is only valid for target d1", query.context());
        }
        Ok(())
    }

    fn render_module(queries: &[Query], _config: &Config, project_dir: &Path) -> Result<String> {
        let blocks = queries
            .iter()
            .map(render_query)
            .collect::<Result<Vec<_>>>()?;
        let optional_extension = queries
            .iter()
            .any(|query| matches!(query.cardinality, Cardinality::One | Cardinality::Scalar))
            .then(|| quote! { use rusqlite::OptionalExtension; });
        format_tokens(
            quote! {
                // Auto-generated by d1c. Do not edit.
                #optional_extension

                #(#blocks)*
            },
            project_dir,
        )
    }
}

fn render_query(query: &Query) -> Result<TokenStream> {
    let params = render_params_struct(query);
    let row = render_row_struct(query);
    let function = render_function(query);
    Ok(quote! { #params #row #function })
}

fn render_params_struct(query: &Query) -> TokenStream {
    if query.parameters.is_empty() {
        return TokenStream::new();
    }
    let name = format_ident!("{}Params", query.name.to_pascal_case());
    let borrowed = query.parameters.iter().any(|parameter| {
        matches!(
            parameter
                .rust_type
                .as_ref()
                .expect("analyzed parameter")
                .source
                .as_str(),
            "String" | "Vec<u8>" | "Option<String>" | "Option<Vec<u8>>"
        )
    });
    let fields = query.parameters.iter().map(|parameter| {
        let field = format_ident!("{}", parameter.rust_name);
        let rust_type =
            rusqlite_input_type(parameter.rust_type.as_ref().expect("analyzed parameter"));
        quote! { pub #field: #rust_type }
    });
    if borrowed {
        quote! {
            #[derive(Debug, Clone)]
            pub struct #name<'a> { #(#fields,)* }
        }
    } else {
        quote! {
            #[derive(Debug, Clone)]
            pub struct #name { #(#fields,)* }
        }
    }
}

fn render_row_struct(query: &Query) -> TokenStream {
    if matches!(query.cardinality, Cardinality::Exec | Cardinality::Scalar) {
        return TokenStream::new();
    }
    let name = format_ident!("{}Row", query.name.to_pascal_case());
    let fields = query.columns.iter().map(|column| {
        let field = format_ident!("{}", column.rust_name);
        let rust_type = &column.rust_type.syntax;
        quote! { pub #field: #rust_type }
    });
    quote! {
        #[derive(Debug, Clone, PartialEq)]
        pub struct #name { #(#fields,)* }
    }
}

fn render_function(query: &Query) -> TokenStream {
    let name = format_ident!("{}", query.rust_name);
    let sql = &query.named_sql;
    let parameter_argument = params_argument(query);
    let bindings = named_bindings(query);
    let row_name = format_ident!("{}Row", query.name.to_pascal_case());
    let row_mapper = row_mapper(query, &row_name);

    match query.cardinality {
        Cardinality::Exec => quote! {
            pub fn #name(
                connection: &rusqlite::Connection,
                #parameter_argument
            ) -> rusqlite::Result<usize> {
                const SQL: &str = #sql;
                connection.execute(SQL, #bindings)
            }
        },
        Cardinality::One => quote! {
            pub fn #name(
                connection: &rusqlite::Connection,
                #parameter_argument
            ) -> rusqlite::Result<Option<#row_name>> {
                const SQL: &str = #sql;
                let mut statement = connection.prepare_cached(SQL)?;
                statement.query_row(#bindings, #row_mapper).optional()
            }
        },
        Cardinality::Many => quote! {
            pub fn #name(
                connection: &rusqlite::Connection,
                #parameter_argument
            ) -> rusqlite::Result<Vec<#row_name>> {
                const SQL: &str = #sql;
                let mut statement = connection.prepare_cached(SQL)?;
                let rows = statement.query_map(#bindings, #row_mapper)?;
                rows.collect()
            }
        },
        Cardinality::Scalar => {
            let rust_type = &query.columns[0].rust_type.syntax;
            let value_column = format_ident!(
                "COLUMN_{}",
                query.columns[0].rust_name.to_shouty_snake_case()
            );
            quote! {
                pub fn #name(
                    connection: &rusqlite::Connection,
                    #parameter_argument
                ) -> rusqlite::Result<Option<#rust_type>> {
                    const SQL: &str = #sql;
                    const #value_column: usize = 0;
                    let mut statement = connection.prepare_cached(SQL)?;
                    statement
                        .query_row(#bindings, |row| row.get(#value_column))
                        .optional()
                }
            }
        }
    }
}

fn params_argument(query: &Query) -> TokenStream {
    if query.parameters.is_empty() {
        return TokenStream::new();
    }
    let name = format_ident!("{}Params", query.name.to_pascal_case());
    let borrowed = query.parameters.iter().any(|parameter| {
        matches!(
            parameter
                .rust_type
                .as_ref()
                .expect("analyzed parameter")
                .source
                .as_str(),
            "String" | "Vec<u8>" | "Option<String>" | "Option<Vec<u8>>"
        )
    });
    if borrowed {
        quote! { params: &#name<'_>, }
    } else {
        quote! { params: &#name, }
    }
}

fn named_bindings(query: &Query) -> TokenStream {
    if query.parameters.is_empty() {
        return quote! { rusqlite::params![] };
    }
    let entries = query.parameters.iter().map(|parameter| {
        let sql_name = format!(":{}", parameter.sql_name);
        let field = format_ident!("{}", parameter.rust_name);
        quote! { #sql_name: params.#field }
    });
    quote! { rusqlite::named_params! { #(#entries,)* } }
}

fn row_mapper(query: &Query, row_name: &proc_macro2::Ident) -> TokenStream {
    let constants = query.columns.iter().enumerate().map(|(index, column)| {
        let name = format_ident!("COLUMN_{}", column.rust_name.to_shouty_snake_case());
        quote! { const #name: usize = #index; }
    });
    let fields = query.columns.iter().map(|column| {
        let field = format_ident!("{}", column.rust_name);
        let index = format_ident!("COLUMN_{}", column.rust_name.to_shouty_snake_case());
        quote! { #field: row.get(#index)? }
    });
    quote! {
        |row| {
            #(#constants)*
            Ok(#row_name { #(#fields,)* })
        }
    }
}

fn rusqlite_input_type(rust_type: &TypeSpec) -> TokenStream {
    match rust_type.source.as_str() {
        "String" => quote! { &'a str },
        "Vec<u8>" => quote! { &'a [u8] },
        "Option<String>" => quote! { Option<&'a str> },
        "Option<Vec<u8>>" => quote! { Option<&'a [u8]> },
        _ => {
            let syntax = &rust_type.syntax;
            quote! { #syntax }
        }
    }
}
