use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};
use heck::ToSnakeCase;

use crate::{
    config::Config,
    query::{analyze_queries, parse_query_file, Query},
    render,
    schema::{collect_sql_files, Schema},
};

const GENERATED_HEADER: &str = "// Auto-generated by d1c. Do not edit.";

#[derive(Debug, Clone)]
pub struct GenerationPlan {
    pub files: BTreeMap<PathBuf, String>,
    generated_module_dir: PathBuf,
    managed_optional_files: BTreeSet<PathBuf>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerationReport {
    pub written: Vec<PathBuf>,
    pub unchanged: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CheckReport {
    pub checked: Vec<PathBuf>,
}

pub fn plan(config: &Config, base_dir: impl AsRef<Path>) -> Result<GenerationPlan> {
    config.validate()?;
    let base_dir = base_dir.as_ref();
    let migrations_dir = base_dir.join(&config.migrations_dir);
    let queries_dir = base_dir.join(&config.queries_dir);
    let out_dir = base_dir.join(&config.out_dir);
    let schema = Schema::replay(&migrations_dir)?;

    let query_files = collect_sql_files(&queries_dir)?;
    let mut grouped: BTreeMap<String, Vec<Query>> = BTreeMap::new();
    let mut module_sources = BTreeMap::<String, PathBuf>::new();
    for query_file in query_files {
        let file_stem = query_file
            .file_stem()
            .context("query path has no file stem")?
            .to_string_lossy()
            .to_snake_case();
        syn::parse_str::<syn::Ident>(&file_stem).with_context(|| {
            format!(
                "query file {} cannot become a Rust module",
                query_file.display()
            )
        })?;
        if file_stem == "mod" {
            bail!(
                "query file {} conflicts with Rust module name `mod`",
                query_file.display()
            );
        }
        if let Some(previous) = module_sources.insert(file_stem.clone(), query_file.clone()) {
            bail!(
                "query files {} and {} collide on generated module `{file_stem}`",
                previous.display(),
                query_file.display()
            );
        }
        let mut queries = parse_query_file(&query_file)?;
        analyze_queries(schema.connection(), &mut queries)?;
        grouped.insert(file_stem, queries);
    }

    let root_file_name = if config.module_name.ends_with(".rs") {
        config.module_name.clone()
    } else {
        format!("{}.rs", config.module_name)
    };
    let root_stem = Path::new(&root_file_name)
        .file_stem()
        .context("module_name has no file stem")?
        .to_string_lossy()
        .to_string();
    if grouped.contains_key(&root_stem) {
        bail!("query module `{root_stem}` conflicts with root generated module");
    }
    let module_dir = out_dir.join(&root_stem);
    let migration_manifest_path = out_dir.join("migrations.rs");
    let managed_optional_files = BTreeSet::from([migration_manifest_path.clone()]);
    let mut files = BTreeMap::new();
    for (module, queries) in &grouped {
        files.insert(
            module_dir.join(format!("{module}.rs")),
            render::render_module(queries, config, base_dir)
                .with_context(|| format!("render target {} module `{module}`", config.target))?,
        );
    }

    let mut root = String::from("// Auto-generated by d1c. Do not edit.\n\n");
    for module in grouped.keys() {
        root.push_str(&format!("pub mod {module};\n"));
    }
    files.insert(out_dir.join(root_file_name), root);
    if config.emit_migrations {
        ensure_generator_owned_or_missing(&migration_manifest_path)?;
        files.insert(
            migration_manifest_path,
            render::migrations::render_manifest(
                schema.migrations(),
                &out_dir.join("migrations.rs"),
                base_dir,
            )
            .context("render migration manifest")?,
        );
    }
    if config.emit_schema {
        files.insert(queries_dir.join("schema.sql"), schema.dump()?);
    }

    Ok(GenerationPlan {
        files,
        generated_module_dir: module_dir,
        managed_optional_files,
    })
}

pub fn generate(config: &Config, base_dir: impl AsRef<Path>) -> Result<GenerationReport> {
    let plan = plan(config, base_dir)?;
    apply(plan)
}

pub fn check(config: &Config, base_dir: impl AsRef<Path>) -> Result<CheckReport> {
    let plan = plan(config, base_dir)?;
    let mut diagnostics = Vec::new();
    let mut checked = Vec::new();
    for (path, expected) in &plan.files {
        match fs::read_to_string(path) {
            Ok(actual) if actual == *expected => checked.push(path.clone()),
            Ok(_) => diagnostics.push(format!("stale: {}", path.display())),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                diagnostics.push(format!("missing: {}", path.display()));
            }
            Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
        }
    }
    for extra in stale_generated_files(&plan)? {
        diagnostics.push(format!("extra: {}", extra.display()));
    }
    if !diagnostics.is_empty() {
        bail!("generated output differs:\n{}", diagnostics.join("\n"));
    }
    Ok(CheckReport { checked })
}

fn apply(plan: GenerationPlan) -> Result<GenerationReport> {
    let stale = stale_generated_files(&plan)?;
    let mut written = Vec::new();
    let mut unchanged = Vec::new();

    // The full parse/analyze/render plan is already complete in memory. Filesystem
    // mutation starts only after every query and target renderer has succeeded.
    for (path, content) in &plan.files {
        if fs::read_to_string(path).ok().as_deref() == Some(content.as_str()) {
            unchanged.push(path.clone());
            continue;
        }
        let parent = path.parent().context("generated output has no parent")?;
        fs::create_dir_all(parent)
            .with_context(|| format!("create generated directory {}", parent.display()))?;
        let mut temporary = tempfile::NamedTempFile::new_in(parent)
            .with_context(|| format!("stage generated file in {}", parent.display()))?;
        use std::io::Write;
        temporary.write_all(content.as_bytes())?;
        temporary.flush()?;
        temporary
            .persist(path)
            .map_err(|error| error.error)
            .with_context(|| format!("replace generated file {}", path.display()))?;
        written.push(path.clone());
    }

    let mut removed = Vec::new();
    for path in stale {
        fs::remove_file(&path)
            .with_context(|| format!("remove stale generated module {}", path.display()))?;
        removed.push(path);
    }
    Ok(GenerationReport {
        written,
        unchanged,
        removed,
    })
}

fn stale_generated_files(plan: &GenerationPlan) -> Result<Vec<PathBuf>> {
    let expected = plan.files.keys().collect::<BTreeSet<_>>();
    let mut stale = Vec::new();
    if plan.generated_module_dir.exists() {
        stale.extend(
            fs::read_dir(&plan.generated_module_dir)?
                .collect::<std::result::Result<Vec<_>, _>>()?
                .into_iter()
                .map(|entry| entry.path())
                .filter(|path| {
                    path.is_file() && path.extension().is_some_and(|extension| extension == "rs")
                })
                .filter(|path| !expected.contains(path)),
        );
    }
    stale.extend(
        plan.managed_optional_files
            .iter()
            .filter(|path| !expected.contains(path))
            .filter(|path| is_generated_file(path))
            .cloned(),
    );
    stale.sort();
    stale.dedup();
    Ok(stale)
}

fn ensure_generator_owned_or_missing(path: &Path) -> Result<()> {
    if path.exists() && !is_generated_file(path) {
        bail!(
            "refusing to overwrite non-generated migration manifest {}",
            path.display()
        );
    }
    Ok(())
}

fn is_generated_file(path: &Path) -> bool {
    fs::read_to_string(path).is_ok_and(|source| source.starts_with(GENERATED_HEADER))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use crate::config::Target;

    use super::*;

    fn fixture(target: Target) -> (tempfile::TempDir, Config) {
        let root = tempdir().unwrap();
        fs::create_dir_all(root.path().join("db/migrations")).unwrap();
        fs::create_dir_all(root.path().join("db/queries")).unwrap();
        fs::write(
            root.path().join("db/migrations/001.sql"),
            "CREATE TABLE item(id INTEGER PRIMARY KEY, name TEXT NOT NULL);",
        )
        .unwrap();
        fs::write(
            root.path().join("db/queries/items.sql"),
            "-- name: ListItems :many\nSELECT id, name FROM item;",
        )
        .unwrap();
        let config = Config {
            version: 1,
            target,
            migrations_dir: "db/migrations".into(),
            queries_dir: "db/queries".into(),
            out_dir: "src/generated".into(),
            module_name: "queries".into(),
            emit_schema: true,
            emit_migrations: false,
            instrument_by_default: false,
        };
        (root, config)
    }

    #[test]
    fn generation_is_deterministic_and_check_detects_drift() {
        let (root, config) = fixture(Target::Rusqlite);
        let first = generate(&config, root.path()).unwrap();
        assert!(!first.written.is_empty());
        let second = generate(&config, root.path()).unwrap();
        assert!(second.written.is_empty());
        check(&config, root.path()).unwrap();
        fs::write(root.path().join("src/generated/queries/items.rs"), "stale").unwrap();
        assert!(check(&config, root.path()).is_err());
        generate(&config, root.path()).unwrap();
        check(&config, root.path()).unwrap();
    }

    #[test]
    fn failures_do_not_modify_existing_output_and_stale_files_are_removed() {
        let (root, config) = fixture(Target::Rusqlite);
        generate(&config, root.path()).unwrap();
        let output = root.path().join("src/generated/queries/items.rs");
        let before = fs::read(&output).unwrap();
        fs::write(root.path().join("src/generated/queries/stale.rs"), "stale").unwrap();
        fs::write(
            root.path().join("db/queries/items.sql"),
            "-- name: Broken :many\nSELECT missing FROM absent;",
        )
        .unwrap();
        assert!(generate(&config, root.path()).is_err());
        assert_eq!(fs::read(&output).unwrap(), before);
        assert!(root.path().join("src/generated/queries/stale.rs").exists());
        fs::write(
            root.path().join("db/queries/items.sql"),
            "-- name: ListItems :many\nSELECT id, name FROM item;",
        )
        .unwrap();
        generate(&config, root.path()).unwrap();
        assert!(!root.path().join("src/generated/queries/stale.rs").exists());
    }

    #[test]
    fn targets_do_not_leak_imports() {
        let (d1_root, d1) = fixture(Target::D1);
        let d1_plan = plan(&d1, d1_root.path()).unwrap();
        let d1_source = d1_plan.files.values().cloned().collect::<String>();
        assert!(d1_source.contains("worker::D1Database"));
        assert!(!d1_source.contains("rusqlite"));

        let (sqlite_root, sqlite) = fixture(Target::Rusqlite);
        let sqlite_plan = plan(&sqlite, sqlite_root.path()).unwrap();
        let sqlite_source = sqlite_plan.files.values().cloned().collect::<String>();
        assert!(sqlite_source.contains("rusqlite"));
        assert!(!sqlite_source.contains("worker::"));
        assert!(!sqlite_source.contains("hb_d1c"));
        assert!(!sqlite_source.contains("OptionalExtension"));
    }

    #[test]
    fn rusqlite_imports_optional_extension_only_for_optional_cardinalities() {
        let (root, config) = fixture(Target::Rusqlite);
        let many_source = plan(&config, root.path())
            .unwrap()
            .files
            .values()
            .cloned()
            .collect::<String>();
        assert!(!many_source.contains("OptionalExtension"));

        fs::write(
            root.path().join("db/queries/items.sql"),
            "-- name: GetItem :one\nSELECT id, name FROM item;",
        )
        .unwrap();
        let one_source = plan(&config, root.path())
            .unwrap()
            .files
            .values()
            .cloned()
            .collect::<String>();
        assert!(one_source.contains("use rusqlite::OptionalExtension;"));
    }

    #[test]
    fn migration_manifest_tracks_content_and_is_removed_when_disabled() {
        let (root, mut config) = fixture(Target::Rusqlite);
        config.emit_schema = false;
        config.emit_migrations = true;
        generate(&config, root.path()).unwrap();
        let manifest = root.path().join("src/generated/migrations.rs");
        let first = fs::read_to_string(&manifest).unwrap();
        assert!(first.contains("id: \"001.sql\""));
        assert!(first.contains("include_str!(\"../../db/migrations/001.sql\")"));
        assert!(first.contains("sha256:"));
        check(&config, root.path()).unwrap();

        fs::write(
            root.path().join("db/migrations/001.sql"),
            "CREATE TABLE item(id INTEGER PRIMARY KEY, name TEXT NOT NULL, active BOOL NOT NULL);",
        )
        .unwrap();
        assert!(check(&config, root.path()).is_err());
        generate(&config, root.path()).unwrap();
        assert_ne!(fs::read_to_string(&manifest).unwrap(), first);

        config.emit_migrations = false;
        assert!(check(&config, root.path()).is_err());
        let report = generate(&config, root.path()).unwrap();
        assert_eq!(report.removed.as_slice(), std::slice::from_ref(&manifest));
        assert!(!manifest.exists());
    }

    #[test]
    fn migration_manifest_never_overwrites_handwritten_source() {
        let (root, mut config) = fixture(Target::Rusqlite);
        let manifest = root.path().join("src/generated/migrations.rs");
        fs::create_dir_all(manifest.parent().unwrap()).unwrap();
        fs::write(&manifest, "pub const HANDWRITTEN: bool = true;\n").unwrap();

        generate(&config, root.path()).unwrap();
        assert_eq!(
            fs::read_to_string(&manifest).unwrap(),
            "pub const HANDWRITTEN: bool = true;\n"
        );
        config.emit_migrations = true;
        assert!(plan(&config, root.path()).is_err());
    }

    #[test]
    fn generated_rust_is_rustfmt_idempotent() {
        let (root, config) = fixture(Target::Rusqlite);
        let plan = plan(&config, root.path()).unwrap();
        for (path, source) in plan
            .files
            .iter()
            .filter(|(path, _)| path.extension().is_some_and(|extension| extension == "rs"))
        {
            let formatted = crate::render::format_rust(source, root.path()).unwrap();
            assert_eq!(
                formatted,
                *source,
                "generated file {} changed under rustfmt",
                path.display()
            );
        }
    }
}
